version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sito-paulo-zefi-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sito_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sito-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sito-paulo-zefi-backend
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5432/sito_db?schema=public
      JWT_SECRET: super_secret_key
      JWT_EXPIRATION: 24h
    depends_on:
      - postgres
    volumes:
      - ./backend/src:/app/src
    networks:
      - sito-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sito-paulo-zefi-frontend
    ports:
      - '4200:4200'
    environment:
      API_URL: http://localhost:3000
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
    networks:
      - sito-network

volumes:
  postgres_data:

networks:
  sito-network:
    driver: bridge
